# Generated by Django 5.2.5 on 2025-08-29 08:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reflect', '0001_initial'),
        ('user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reflect',
            name='response',
        ),
        migrations.AddField(
            model_name='reflect',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='reflect_attachments/'),
        ),
        migrations.AddField(
            model_name='reflect',
            name='bo_mon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reflects', to='user.bomon'),
        ),
        migrations.AddField(
            model_name='reflect',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reflects', to='reflect.type'),
        ),
        migrations.CreateModel(
            name='ReflectResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='reflect_response_attachments/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('reflect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='reflect.reflect')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reflect_responses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
