# Generated by Django 5.2.5 on 2025-08-30 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reflect', '0002_remove_reflect_response_reflect_attachment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Tiêu đề khảo sát')),
                ('link', models.URLField(verbose_name='Link khảo sát')),
                ('status', models.CharField(choices=[('active', 'Đang mở'), ('inactive', 'Tạm dừng'), ('closed', 'Đã đóng')], default='active', max_length=10, verbose_name='Trạng thái')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Ngày kết thúc')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Khảo sát',
                'verbose_name_plural': 'Khảo sát',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='reflectresponse',
            name='rating',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
