# Generated by Django 5.2.5 on 2025-09-03 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reflect', '0003_survey_alter_reflectresponse_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='reflect',
            name='anonymous',
            field=models.BooleanField(default=False),
        ),
    ]
