# Generated by Django 5.2.5 on 2025-09-03 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reflect', '0004_reflect_anonymous'),
    ]

    operations = [
        migrations.AddField(
            model_name='reflect',
            name='status',
            field=models.CharField(choices=[('create', 'Mở'), ('active', 'Đã xử'), ('done', 'Kết thúc'), ('cancel', 'Hủy bỏ')], default='create', max_length=10),
        ),
    ]
