# Generated by Django 5.2.5 on 2025-09-04 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reflect', '0005_reflect_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reflect',
            name='status',
            field=models.CharField(choices=[('create', 'Đang mở'), ('active', 'Đã xử'), ('done', 'Kết thúc'), ('cancel', 'Hủy bỏ')], default='create', max_length=10),
        ),
    ]
