# Generated by Django 5.2.5 on 2025-08-29 04:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BoMon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='GV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ho_ten', models.CharField(max_length=255, verbose_name='Họ và tên')),
                ('ngay_sinh', models.DateField(verbose_name='Ngày sinh')),
                ('gioi_tinh', models.CharField(choices=[('Nam', 'Nam'), ('Nữ', 'Nữ')], max_length=10, verbose_name='Giới tính')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('so_dien_thoai', models.CharField(blank=True, max_length=15, null=True, verbose_name='Điện thoại')),
                ('can_cuoc', models.CharField(blank=True, max_length=20, null=True, verbose_name='Căn cước công dân')),
                ('ngay_cap', models.DateField(blank=True, null=True, verbose_name='Ngày cấp')),
                ('noi_cap', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nơi cấp')),
                ('chuc_vu', models.CharField(blank=True, max_length=255, null=True, verbose_name='Chức vụ')),
                ('status', models.CharField(choices=[('P', 'Pending'), ('A', 'Active'), ('R', 'Rejected')], default='P', max_length=1)),
                ('bo_mon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.bomon')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gv', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Giảng viên',
                'verbose_name_plural': 'Danh sách Giảng viên',
                'ordering': ['ho_ten'],
            },
        ),
        migrations.CreateModel(
            name='SV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ho_ten', models.CharField(max_length=255, verbose_name='Họ và tên')),
                ('ngay_sinh', models.DateField(verbose_name='Ngày sinh')),
                ('gioi_tinh', models.CharField(choices=[('Nam', 'Nam'), ('Nữ', 'Nữ')], max_length=10, verbose_name='Giới tính')),
                ('noi_sinh', models.CharField(max_length=255, verbose_name='Nơi sinh')),
                ('dan_toc', models.CharField(max_length=50, verbose_name='Dân tộc')),
                ('que_quan', models.CharField(max_length=255, verbose_name='Quê quán')),
                ('email', models.EmailField(max_length=254, verbose_name='Địa chỉ email')),
                ('so_hieu_cong_an', models.CharField(blank=True, max_length=50, null=True, verbose_name='Số hiệu CAND')),
                ('can_cuoc', models.CharField(blank=True, max_length=20, null=True, verbose_name='Căn cước công dân')),
                ('ngay_cap', models.DateField(blank=True, null=True, verbose_name='Ngày cấp')),
                ('noi_cap', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nơi cấp')),
                ('dia_chi_lien_lac', models.CharField(blank=True, max_length=255, null=True, verbose_name='Địa chỉ liên lạc')),
                ('dien_thoai', models.CharField(blank=True, max_length=15, null=True, verbose_name='Điện thoại di động')),
                ('lop', models.CharField(blank=True, max_length=255, null=True, verbose_name='Lớp')),
                ('khoa', models.CharField(blank=True, max_length=255, null=True, verbose_name='Khóa')),
                ('status', models.CharField(choices=[('P', 'Pending'), ('A', 'Active'), ('R', 'Rejected')], default='P', max_length=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sv', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sinh viên',
                'verbose_name_plural': 'Danh sách Sinh viên',
                'ordering': ['ho_ten'],
            },
        ),
    ]
