# Generated by Django 5.2.5 on 2025-08-25 04:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ho_ten', models.CharField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ho_ten', models.CharField(max_length=255, verbose_name='Họ và tên')),
                ('ngay_sinh', models.DateField(verbose_name='Ngày sinh')),
                ('gioi_tinh', models.CharField(choices=[('Nam', 'Nam'), ('Nữ', 'Nữ')], max_length=10, verbose_name='Giới tính')),
                ('noi_sinh', models.CharField(max_length=255, verbose_name='Nơi sinh')),
                ('dan_toc', models.CharField(max_length=50, verbose_name='Dân tộc')),
                ('que_quan', models.CharField(max_length=255, verbose_name='Quê quán')),
                ('email', models.EmailField(max_length=254, verbose_name='Địa chỉ email')),
                ('so_hieu_cong_an', models.CharField(blank=True, max_length=50, null=True, verbose_name='Số hiệu Công an nhân dân')),
                ('can_cuoc', models.CharField(blank=True, max_length=20, null=True, verbose_name='Căn cước công dân')),
                ('ngay_cap', models.DateField(blank=True, null=True, verbose_name='Ngày cấp')),
                ('noi_cap', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nơi cấp')),
                ('dia_chi_lien_lac', models.CharField(blank=True, max_length=255, null=True, verbose_name='Địa chỉ liên lạc')),
                ('dien_thoai', models.CharField(blank=True, max_length=15, null=True, verbose_name='Điện thoại di động')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sv', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
