# Generated by Django 5.2.5 on 2025-08-25 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_sv_khoa_sv_lop'),
    ]

    operations = [
        migrations.AddField(
            model_name='sv',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('A', 'Active'), ('R', 'Rejected')], default='P', max_length=1),
        ),
    ]
